# Naive Bayes Classifier - Play Tennis Dataset

This notebook builds a **Categorical Naive Bayes** model on the Play Tennis dataset, evaluates it with a train/test split, and compares its performance against a Decision Tree and Logistic Regression.

In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

## Step 1: Create the dataset

In [2]:
data = {
    'Outlook': ['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny','Sunny','Rain',
                'Sunny','Overcast','Overcast','Rain','Sunny','Sunny','Sunny','Sunny','Overcast','Overcast',
                'Overcast','Overcast','Rain','Rain','Rain','Rain','Rain','Rain','Rain','Sunny',
                'Sunny','Sunny','Sunny','Sunny','Overcast','Overcast','Overcast','Overcast','Rain','Rain',
                'Rain','Sunny','Sunny','Sunny','Overcast','Overcast','Rain','Rain','Sunny','Overcast'],

    'Temperature': ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild',
                     'Mild','Mild','Hot','Mild','Cool','Cool','Hot','Hot','Cool','Cool',
                     'Mild','Mild','Hot','Hot','Hot','Hot','Cool','Cool','Mild','Mild',
                     'Cool','Hot','Hot','Mild','Hot','Hot','Cool','Mild','Mild','Cool',
                     'Hot','Cool','Mild','Hot','Cool','Mild','Mild','Cool','Cool','Hot'],

    'Humidity': ['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal',
                 'Normal','High','Normal','High','High','High','Normal','Normal','High','High',
                 'Normal','Normal','High','High','Normal','Normal','High','High','Normal','High',
                 'Normal','High','Normal','Normal','High','Normal','Normal','High','High','Normal',
                 'High','High','Normal','High','High','Normal','Normal','High','Normal','Normal'],

    'Wind': ['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak',
             'Strong','Strong','Weak','Strong','Weak','Strong','Weak','Strong','Weak','Strong',
             'Weak','Strong','Weak','Strong','Weak','Strong','Weak','Strong','Strong','Strong',
             'Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Weak',
             'Strong','Weak','Strong','Strong','Weak','Strong','Weak','Strong','Weak','Weak'],

    'Play Tennis': ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes',
                     'Yes','Yes','Yes','No','No','No','Yes','Yes','Yes','Yes',
                     'Yes','Yes','Yes','No','Yes','No','Yes','No','Yes','No',
                     'Yes','No','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes',
                     'No','No','Yes','No','Yes','Yes','Yes','No','Yes','Yes']
}

df = pd.DataFrame(data)

print("Dataset")
print(df)
print("\nShape:", df.shape)

Dataset
     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No
14     Sunny        Cool     High    Weak          No
15     Sunny        Cool     High  Strong          No
16     Sunny         Hot   Normal    Weak         Yes
17     Sunny        

## Step 2: Separate input features (X) and target variable (y)

In [3]:
X = df[['Outlook', 'Temperature', 'Humidity', 'Wind']]
y = df['Play Tennis']

print("Features (X)")
print(X.head())

print("\nTarget (y)")
print(y.head())

Features (X)
    Outlook Temperature Humidity    Wind
0     Sunny         Hot     High    Weak
1     Sunny         Hot     High  Strong
2  Overcast         Hot     High    Weak
3      Rain        Mild     High    Weak
4      Rain        Cool   Normal    Weak

Target (y)
0     No
1     No
2    Yes
3    Yes
4    Yes
Name: Play Tennis, dtype: str


## Step 3: Convert categorical values into numerical values

`CategoricalNB` needs integer-encoded categories, so we use `OrdinalEncoder` to convert each categorical column into numbers.

In [4]:
encoder = OrdinalEncoder()
X_encoded = encoder.fit_transform(X)

print("Encoding used for each feature:")
for col, cats in zip(X.columns, encoder.categories_):
    print(f"  {col}: {list(cats)}")

print("\nEncoded Features (first 5 rows)")
print(X_encoded[:5])

Encoding used for each feature:
  Outlook: ['Overcast', 'Rain', 'Sunny']
  Temperature: ['Cool', 'Hot', 'Mild']
  Humidity: ['High', 'Normal']
  Wind: ['Strong', 'Weak']

Encoded Features (first 5 rows)
[[2. 1. 0. 1.]
 [2. 1. 0. 0.]
 [0. 1. 0. 1.]
 [1. 2. 0. 1.]
 [1. 0. 1. 1.]]


## Step 4: Divide the dataset into training and testing sets

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.3, random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples :", X_test.shape[0])

Training samples: 35
Testing samples : 15


## Step 5: Train a Categorical Naive Bayes model

In [6]:
nb_model = CategoricalNB()
nb_model.fit(X_train, y_train)

print("Naive Bayes model trained.")
print("Classes:", nb_model.classes_)

Naive Bayes model trained.
Classes: ['No' 'Yes']


## Step 6: Predict class labels for the test dataset

In [7]:
y_pred = nb_model.predict(X_test)

print("Predicted labels:", list(map(str, y_pred)))
print("Actual labels   :", list(y_test))

Predicted labels: ['No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']
Actual labels   : ['No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']


## Step 7: Accuracy, confusion matrix, and classification report

In [8]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy of Naive Bayes:", acc)

cm = confusion_matrix(y_test, y_pred, labels=nb_model.classes_)
print("\nConfusion Matrix")
print("Labels order:", list(nb_model.classes_))
print(cm)

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy of Naive Bayes: 0.8

Confusion Matrix
Labels order: [np.str_('No'), np.str_('Yes')]
[[ 1  1]
 [ 2 11]]

Classification Report
              precision    recall  f1-score   support

          No       0.33      0.50      0.40         2
         Yes       0.92      0.85      0.88        13

    accuracy                           0.80        15
   macro avg       0.62      0.67      0.64        15
weighted avg       0.84      0.80      0.82        15



## Step 8: Predict for a new weather condition

Outlook = Sunny, Temperature = Cool, Humidity = High, Wind = Strong

In [9]:
new_data = pd.DataFrame({
    'Outlook': ['Sunny'],
    'Temperature': ['Cool'],
    'Humidity': ['High'],
    'Wind': ['Strong']
})

new_encoded = encoder.transform(new_data)

new_prediction = nb_model.predict(new_encoded)
new_probability = nb_model.predict_proba(new_encoded)

print("New Sample: Outlook=Sunny, Temperature=Cool, Humidity=High, Wind=Strong")
print("\nPredicted Class:", new_prediction[0])

print("\nClass Probabilities:")
for cls, prob in zip(nb_model.classes_, new_probability[0]):
    print(f"  {cls}: {prob:.4f}")

New Sample: Outlook=Sunny, Temperature=Cool, Humidity=High, Wind=Strong

Predicted Class: No

Class Probabilities:
  No: 0.9373
  Yes: 0.0627


## Step 9: Compare performance with Decision Tree and Logistic Regression

In [10]:
# Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_acc = accuracy_score(y_test, dt_pred)

# Logistic Regression
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
lr_acc = accuracy_score(y_test, lr_pred)

print("Model Comparison")
print(f"Naive Bayes Accuracy     : {acc:.4f}")
print(f"Decision Tree Accuracy   : {dt_acc:.4f}")
print(f"Logistic Regression Acc. : {lr_acc:.4f}")

comparison_df = pd.DataFrame({
    'Model': ['Categorical Naive Bayes', 'Decision Tree', 'Logistic Regression'],
    'Accuracy': [acc, dt_acc, lr_acc]
}).sort_values('Accuracy', ascending=False).reset_index(drop=True)

print("\nComparison Table")
print(comparison_df)

Model Comparison
Naive Bayes Accuracy     : 0.8000
Decision Tree Accuracy   : 0.6000
Logistic Regression Acc. : 0.5333

Comparison Table
                     Model  Accuracy
0  Categorical Naive Bayes  0.800000
1            Decision Tree  0.600000
2      Logistic Regression  0.533333


## Observations

- The dataset is small (50 rows, 15 in the test split), so accuracy numbers can shift a fair bit depending on the `random_state` used in the split.
- **Naive Bayes** assumes the features are conditionally independent given the class. Even though that assumption doesn't strictly hold for weather attributes, it still does reasonably well here.
- **Decision Tree** can overfit on small categorical datasets since it keeps splitting on the training data.
- **Logistic Regression** works with the ordinal-encoded numeric features here, but ordinal encoding imposes an artificial order (e.g., Sunny < Overcast < Rain) that doesn't really exist for a linear model, which can hurt its performance compared to Naive Bayes and Decision Tree, which don't rely on the numeric ordering.

the model works, but it's better at predicting "yes, they'll play" than "no, they won't"  mainly because it saw far more "yes" examples during training.